name: Auto build

on:
  push:
    branches:
      - master

jobs:
  clone-md-book:
    name: Clone md book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: rust-lang/mdBook
      - name: Install hub
        run: ci/install-hub.sh ubuntu-latest
        shell: bash
      - name: Install Rust
        run: ci/install-rust.sh stable aarch64-unknown-linux-musl
        shell: bash